server:
  port: 8013
  servlet:
    context-path: /custom-path
spring:
  application:
    name: serviceorder
  data:
    mongodb:
      uri: mongodb+srv://user_test:user_test@prueba.or9uj6t.mongodb.net/?retryWrites=true&w=majority&appName=prueba
      database: keoladb